//
//  AIDisclosureView.swift
//  H2Oe
//
//  Transparency notice for the app's machine-learning forecasts (EU AI Act,
//  Reg. 2024/1689, Art. 50): the discharge (Q) forecasts and HQ flood-level
//  warnings are AI-generated. `AIDisclosureView` is the first-launch modal the
//  user must acknowledge; `AIGeneratedNote` is the persistent inline hint shown
//  wherever a forecast is displayed.
//

import SwiftUI

struct AIDisclosureView: View {
    let onAcknowledge: () -> Void

    var body: some View {
        VStack(spacing: 0) {
            ScrollView {
                VStack(alignment: .leading, spacing: 18) {
                    VStack(alignment: .leading, spacing: 10) {
                        Image(systemName: "sparkles")
                            .font(.largeTitle)
                            .foregroundStyle(.cyan)
                            .accessibilityHidden(true)
                        Text("AI-generated forecasts")
                            .font(.title.bold())
                    }

                    Text("H2Ö shows discharge (Q) forecasts and flood-level (HQ) warnings that are produced automatically by a machine-learning model.")
                        .font(.body)
                        .fixedSize(horizontal: false, vertical: true)

                    row("cpu", "The forecasts and warnings are generated by an AI model and can be inaccurate or incomplete.")
                    row("exclamationmark.triangle", "They are not official flood warnings and must not be the only basis for safety decisions.")
                    row("checkmark.shield", "In an emergency, always follow the official warnings of the responsible authorities.")

                    Link(destination: URL(string: "https://www.noel.gv.at/wasserstand/")!) {
                        Text("Official water levels & warnings: noe.gv.at")
                            .font(.footnote)
                            .frame(minHeight: 44, alignment: .leading)
                            .contentShape(Rectangle())
                    }
                }
                .padding(24)
            }

            Button(action: onAcknowledge) {
                Text("I understand")
                    .font(.headline)
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 14)
            }
            .buttonStyle(.borderedProminent)
            .tint(.cyan)
            .padding(24)
            .background(.ultraThinMaterial)
        }
        .interactiveDismissDisabled()
    }

    private func row(_ symbol: String, _ text: String) -> some View {
        HStack(alignment: .top, spacing: 12) {
            Image(systemName: symbol)
                .font(.body.weight(.semibold))
                .foregroundStyle(.cyan)
                .frame(width: 26)
                .accessibilityHidden(true)
            Text(text)
                .font(.callout)
                .fixedSize(horizontal: false, vertical: true)
        }
    }
}

/// Persistent inline provenance hint shown next to forecast content.
struct AIGeneratedNote: View {
    var body: some View {
        HStack(spacing: 6) {
            Image(systemName: "sparkles")
                .accessibilityHidden(true)
            Text("AI-generated forecast — not an official warning.")
                .fixedSize(horizontal: false, vertical: true)
        }
        .font(.caption2)
        .foregroundStyle(.secondary)
    }
}
